### ISSUE TITLE
MELPA?

### ISSUE THREAD

**Issue by Silex** [gtp/emacs-redmine#2]
Can you add this to MELPA? :)

**Comment by gtp** [comment]
Hi,

I've abandoned redmine in favour of an in-house system, so this
project is unsupported now.

Best Regards,
Gareth Priede
ImplicitDesign
w: +27 21 448 7424
c: +27 72 679 1763
s: garethpriede

At Wed, 04 Jun 2014 05:24:44 -0700,
Philippe Vaucher wrote:

**Comment by Silex** [comment]
Alright, thanks for the info.
